# Text Data Pre-Processing
for Fake News Data

In [1]:
! pip install numpy
! pip install pandas
! pip install nltk
! pip install scikit-learn

Requirement already satisfied: numpy in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (2.5.2)
Requirement already satisfied: pandas in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: nltk in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (3.10.3)
Requirement already satisfied: defusedxml in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (from nltk) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (from nltk) (2026.9.10)
Requirement already satisfied: tqdm in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (from nltk) (4.70.1)
Requirement already satisfied: cloudpickle>=3.0 in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (from joblib->nltk) (3.1.2)
Requirement already satisfied: scikit-learn in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (from scikit-learn) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)

Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd
import re
import nltk 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [2]:
nltk.download('stopwords')

/home/ravinder/drive/work_spaces/python/.venv/lib/python3.14/site-packages/nltk/downloader.py:1076: UserWarning: NLTK will not authorize the non-private download directory '/home/ravinder/nltk_data': it (or an ancestor) is world- or group-writable, so another local user could plant files there. Choose a private location such as ~/nltk_data.
  for msg in self.incr_download(info_or_id, download_dir, force):
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/ravinder/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
# printing the stopwords
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

Data Pre-Processing

In [6]:
# load the data to a pandas dataframe
news_data = pd.read_csv('/home/ravinder/drive/work_spaces/python/datasets/fake_news_dataset.csv')

In [7]:
# first 5 rows of the dataset
news_data.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

0 --> Real News

1 --> Fake News

In [8]:
news_data.shape

(20800, 5)

In [9]:
# checking for missing values
news_data.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [10]:
# replacing the missing values with null string
news_data = news_data.fillna('')

In [11]:
# merging th eauthor name and news title
news_data['content'] = news_data['author']+' '+news_data['title']

In [12]:
# first 5 rows of the dataset
news_data.head()

,id,title,author,text,label,content
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1,Darrell Lucus House Dem Aide: We Didn’t Even S...
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0,"Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo..."
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1,Consortiumnews.com Why the Truth Might Get You...
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1,Jessica Purkiss 15 Civilians Killed In Single ...
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1,Howard Portnoy Iranian woman jailed for fictio...

In [14]:
# separating feature and target
X = news_data.drop(columns='label')
Y = news_data['label']

In [16]:
print(X)

          id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...
2          2                  Why the Truth Might Get You Fired
3          3  15 Civilians Killed In Single US Airstrike Hav...
4          4  Iranian woman jailed for fictional unpublished...
...      ...                                                ...
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...
20797  20797  Macy’s Is Said to Receive Takeover Approach by...
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...
20799  20799                          What Keeps the F-35 Alive

                                          author  \
0                                  Darrell Lucus
1                                Daniel J. Flynn
2                             Consortiumnews.com
3                                Jessica Purkiss
4                                 Howard Portnoy
...                                          ...
20795                              Jerome Hudson
20796                           Benjamin Hoffman
20797  Michael J. de la Merced and Rachel Abrams
20798                                Alex Ansary
20799                              David Swanson

                                                    text  \
0      House Dem Aide: We Didn’t Even See Comey’s Let...
1      Ever get the feeling your life circles the rou...
2      Why the Truth Might Get You Fired October 29, ...
3      Videos 15 Civilians Killed In Single US Airstr...
4      Print \nAn Iranian woman has been sentenced to...
...                                                  ...
20795  Rapper T. I. unloaded on black celebrities who...
20796  When the Green Bay Packers lost to the Washing...
20797  The Macy’s of today grew from the union of sev...
20798  NATO, Russia To Hold Parallel Exercises In Bal...
20799    David Swanson is an author, activist, journa...

                                                 content
0      Darrell Lucus House Dem Aide: We Didn’t Even S...
1      Daniel J. Flynn FLYNN: Hillary Clinton, Big Wo...
2      Consortiumnews.com Why the Truth Might Get You...
3      Jessica Purkiss 15 Civilians Killed In Single ...
4      Howard Portnoy Iranian woman jailed for fictio...
...                                                  ...
20795  Jerome Hudson Rapper T.I.: Trump a ’Poster Chi...
20796  Benjamin Hoffman N.F.L. Playoffs: Schedule, Ma...
20797  Michael J. de la Merced and Rachel Abrams Macy...
20798  Alex Ansary NATO, Russia To Hold Parallel Exer...
20799            David Swanson What Keeps the F-35 Alive

[20800 rows x 5 columns]

In [15]:
print(Y)

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 20800, dtype: int64

Stemming:

Stemming is the process of reducing a word to its Root Word

In [17]:
port_stem = PorterStemmer()

In [40]:
def stemming(content):
  stemmed_content = re.sub('[^a-zA-Z]',' ',content)
  stemmed_content = stemmed_content.lower()
  stemmed_content = stemmed_content.split()
  stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
  stemmed_content = ' '.join(stemmed_content)
  return stemmed_content

In [41]:
news_data['content'] = news_data['content'].apply(stemming)

In [42]:
print(news_data['content'])

0        darrel lucu hou dem aid even see comey letter ...
1        daniel j flynn flynn hillari clinton big woman...
2                   consortiumnew com truth might get fire
3        jessica purkiss civilian kill singl us airstri...
4        howard portnoy iranian woman jail fiction unpu...
                               ...
20795    jerom hudson rapper trump poster child white s...
20796    benjamin hoffman n f l playoff schedul matchup...
20797    michael j de la merc rachel abram maci said re...
20798    alex ansari nato russia hold parallel exerci b...
20799                            david swanson keep f aliv
Name: content, Length: 20800, dtype: str

In [64]:
X = news_data['content'].values
Y = news_data['label'].values

In [65]:
print(X)

<ArrowStringArray>
[                                              'darrel lucu hou dem aid even see comey letter jason chaffetz tweet',
                                                   'daniel j flynn flynn hillari clinton big woman campu breitbart',
                                                                           'consortiumnew com truth might get fire',
                                                         'jessica purkiss civilian kill singl us airstrik identifi',
                             'howard portnoy iranian woman jail fiction unpublish stori woman stone death adulteri',
 'daniel nussbaum jacki mason hollywood would love trump bomb north korea lack tran bathroom exclu video breitbart',
                                   'life life luxuri elton john favorit shark pictur stare long transcontin flight',
                              'alissa j rubin beno hamon win french socialist parti presidenti nomin new york time',
                                       'excerpt draft script donald trump q ampa black church pastor new york time',
                     'megan twohey scott shane back channel plan ukrain russia courtesi trump associ new york time',
 ...
                                'adam shaw nikki haley blast u n human right offic unfair bia israel latest report',
                                      'daniel greenfield lawyer kept hillari campaign chief jail doj hillari probe',
                                                'john hayward jakarta bomb kill three polic offic link islam state',
                                                'robert rich idiot destroy trump hollywood star get exactli deserv',
                                                  'lee stranahan trump putin smart retali obama sanction breitbart',
                                                           'jerom hudson rapper trump poster child white supremaci',
                                                 'benjamin hoffman n f l playoff schedul matchup odd new york time',
                      'michael j de la merc rachel abram maci said receiv takeov approach hudson bay new york time',
                                                              'alex ansari nato russia hold parallel exerci balkan',
                                                                                        'david swanson keep f aliv']
Length: 20800, dtype: str

In [66]:
print(type(X))
print(X.shape) # Rows, Columns # sentence is like 1 row & every word is like one element

<class 'pandas.arrays.ArrowStringArray'>
(20800,)

In [67]:
print(Y)

[1 0 1 ... 0 1 1]

In [51]:
Y.shape

(20800,)

In [70]:
# converting the textual data to feature vectors
vectorizer = TfidfVectorizer()

vectorizer.fit(X)

X = vectorizer.transform(X)

In [71]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 210584 stored elements and shape (20800, 16984)>
  Coords	Values
  (0, 263)	0.2701012497770876
  (0, 2464)	0.36765196867972083
  (0, 2933)	0.24684501285337127
  (0, 3567)	0.3598939188262558
  (0, 3759)	0.27053324808454915
  (0, 4917)	0.23331696690935097
  (0, 6930)	0.2187416908935914
  (0, 7612)	0.24785219520671598
  (0, 8546)	0.2921251408704368
  (0, 8822)	0.36359638063260746
  (0, 13348)	0.2565896679337956
  (0, 15553)	0.2848506356272864
  (1, 1481)	0.2957471154505952
  (1, 1877)	0.15614790568229528
  (1, 2206)	0.36915639258038363
  (1, 2790)	0.19208753385709676
  (1, 3535)	0.2653147533915268
  (1, 5440)	0.7186013955384664
  (1, 6744)	0.19152496072048605
  (1, 16656)	0.3025156488372128
  (2, 2917)	0.3179886800654691
  (2, 3072)	0.46097489583229645
  (2, 5326)	0.3866530551182615
  (2, 5903)	0.3474613386728292
  (2, 9532)	0.49351492943649944
  :	:
  (20797, 3610)	0.211655450844435
  (20797, 6969)	0.21809398920480086
  (20797, 8282)	0.22333184464489023
  (20797, 8901)	0.3617803783368178
  (20797, 9431)	0.2939494781564304
  (20797, 9500)	0.17463635692029988
  (20797, 10216)	0.0804189541935242
  (20797, 12022)	0.24790022252744132
  (20797, 12227)	0.27276402145717243
  (20797, 12998)	0.2483705036831893
  (20797, 14838)	0.31174247426294605
  (20797, 15164)	0.08163135159577194
  (20797, 16853)	0.08319604116299942
  (20798, 345)	0.2844693781907258
  (20798, 580)	0.3112141524638974
  (20798, 1112)	0.4460515589182237
  (20798, 4974)	0.40837014502395297
  (20798, 6816)	0.3249628569429943
  (20798, 10088)	0.31924963701870285
  (20798, 10949)	0.4460515589182237
  (20798, 12923)	0.2236326748827061
  (20799, 372)	0.5677577267055112
  (20799, 3590)	0.37927626273066584
  (20799, 7955)	0.45983893273780013
  (20799, 14723)	0.5677577267055112

In [72]:
print(type(X))
print(X.shape)

<class 'scipy.sparse._csr.csr_matrix'>
(20800, 16984)